package io.senftresearch.openrd;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;

class RuidaTest {

    private OpenRD rd;

    @BeforeEach
    void setUp() {
        rd = OpenRD.getInstance();
    }

    @Test
    void testRuidaLayerSetup() throws IOException, InterruptedException {
        // 1. Replicate paths_list_mark
        List<RDPoint> markPath1 = List.of(new RDPoint(12, 10), new RDPoint(38, 25), new RDPoint(12, 40), new RDPoint(12, 10));
        List<RDPoint> markPath2 = List.of(new RDPoint(16, 6), new RDPoint(10, 6), new RDPoint(13, 3), new RDPoint(16, 6));
        List<RDPoint> markPath3 = List.of(new RDPoint(60, 6), new RDPoint(54, 6), new RDPoint(57, 3), new RDPoint(60, 6));

        List<List<RDPoint>> pathsListMark = new ArrayList<>();
        pathsListMark.add(markPath1);
        pathsListMark.add(markPath2);
        pathsListMark.add(markPath3);

        // 2. Replicate paths_list_cut
        List<List<RDPoint>> pathsListCut = List.of(List.of(
                new RDPoint(0, 0),
                new RDPoint(50, 0),
                new RDPoint(50, 50),
                new RDPoint(0, 50),
                new RDPoint(0, 0)
        ));

        // 4. Instantiate the individual layers
        RDLayer layer0 = new RDLayer(pathsListMark, 100, new RDPoint(10, 18), new RDColour(0, 255, 0), 20.0f, null);
        RDLayer layer1 = new RDLayer(pathsListCut, 30, new RDPoint(40, 70), new RDColour(255, 0, 0), 20.0f, null);

        // 5. Execute your set method updates
        rd.set(layer0, 0);
        rd.set(layer1, 0);

        // Generates the 'test.rd' payload file
        String filePath = "test.rd";
        rd.write(true, filePath);

        // ==========================================
        // NEW: Test the RuidaUdp Implementation
        // ==========================================

        // 1. Read the raw bytes generated by your OpenRD software
        byte[] rdFileBytes = Files.readAllBytes(Paths.get(filePath));
        assertNotNull(rdFileBytes, "Generated payload should not be null");
        assertTrue(rdFileBytes.length > 0, "Generated payload should contain data");

        // 2. Target IP configuration (Change to your actual Ruida controller IP)
        String ruidaControllerIp = "10.0.0.100";

        // 3. Send over UDP (Wrap in try-with-resources if your class implements AutoCloseable)
        RDUdp udpClient = new RDUdp(ruidaControllerIp);
        try {
            System.out.println("Sending " + rdFileBytes.length + " bytes to Ruida Controller...");

            byte[] response = udpClient.write(rdFileBytes);

            // If response is null, it means every chunk successfully received an ACK
            if (response == null) {
                System.out.println("Transmission successful! All packets acknowledged.");
            } else {
                System.out.printf("Transmission cut short. Non-ACK response received: 0x%02X%n", response[0]);
            }

        } catch (IOException e) {
            System.err.println("Network failure or timeout during transmission: " + e.getMessage());
            throw e;
        } finally {
            udpClient.close();
        }
    }
}
